name: Plugin CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 构建插件信息
        run: |
          cd plugin_release_parse
          npm install
          npm run build

      - name: 构建官网前端
        run: |
          cd web_site_project
          npm install
          npm run docs:build
          cp -r ./docs/.vitepress/dist/* ../pages/

      - name: Deploy Plugin Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pages